apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: mysql
  name: mysql-pv
  labels:
    type: local
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mysql"
